### ISSUE TITLE
Edit existing scheduled tasks

### ISSUE THREAD

**Issue by mrmachine** [ddurdle/Python-GoogleDrive-VideoStream#102]
Is it possible to edit (instead of having to delete and recreate) existing scheduled tasks? Or at least even view an existing task, so I can be sure I correctly remember its current configuration when recreating it so I only change the one setting I want to change?

**Comment by ddurdle** [comment]
you can use the python setup.py script to view, update and delete records.  The job details are stored as job#_cmd.

**Comment by mrmachine** [comment]
@ddurdle I don't follow. I've tried `python setup.py` and it doesn't seem to offer much help or options that would allow me to say change a scheduled job to enable generation of Google Drive transcodes and start appending resolution to files?

```shell
/opt/python-googledrive-videostream # python setup.py --help
Usage: setup.py [option] <key> <value>

Options:
  -h, --help            show this help message and exit
  -a ADD, --add=ADD     Add Settings
  -c CHANGE, --change=CHANGE
                        Change Settings
  -s, --show            Display Settings
  -i IMP, --import=IMP  Import Settings
  -r REMOVE, --remove=REMOVE
                        Remove Settings
  -d DATABASE, --dbase=DATABASE
                        change database
/opt/python-googledrive-videostream # python setup.py -c
Usage: setup.py [option] <key> <value>

setup.py: error: -c option requires 2 arguments
/opt/python-googledrive-videostream # python setup.py -s
____________KEY____________ > __________VALUE__________
```

**Comment by ddurdle** [comment]
run python setup.py -s | grep #_cmd

where # is the job number.  It will return the current value

take the output value, change resolution=false to true

and run
python setup.py -c #_cmd 'string_updated'

**Comment by mrmachine** [comment]
@ddurdle you can see in my log above that `python setup.py -s` doesn't show anything, so grep wouldn't match `#_cmd`.

I run `python default.py /opt/strm/gdrive.db`, but I don't see an option to `setup.py` to specify a non-default database?

**Comment by mrmachine** [comment]
Scratch that. It's `-d`. I'm an idiot.
