### ISSUE TITLE
How to configure with Emby to access Google Drive transcodes?

### ISSUE THREAD

**Issue by mrmachine** [ddurdle/Python-GoogleDrive-VideoStream#104]
I tried this and it seemed to work for movies. Emby would ask me which version to play, with auto being the default, though it put "original" way down the bottom of the list, below the SD transcodes even. Original should be at the top, below auto? The other options are all in descending quality order. Is it based on filename?

But it didn't work for TV at all. I ended up with 4/5 copies of every episode, and watching one would not mark the others as watched. Is this a problem with Emby, or the way I have configured Emby, or the filenames being used etc?

**Comment by ddurdle** [comment]
only Emby 3.6.51 or later supports multiple qualities for TV shows.  But at this point there are a lot of pending fixes in 3.6 that are needed to make the product "usable".  And there is no successful downgrade path for emby to return to a previous version without destroying everything.

**Comment by ddurdle** [comment]
Emby doesn't sort the dropdown list in any way -- completely random ordering.
