### ISSUE TITLE
Recommended interval between scheduled tasks?

### ISSUE THREAD

**Issue by mrmachine** [ddurdle/Python-GoogleDrive-VideoStream#107]
Can you make a recommendation (ideally in the UI when creating scheduled tasks) about a suitable interval to use? Am I likely to hit Google Drive API ban if I set the interval to 1 minute, 5 minutes, or 15 minutes?

Or is Python-GoogleDrive-VideoStream not crawling the remote file system, and only asking Google Drive for a list of changes since the last update, and therefore a 1 minute interval is safe and not likely to trigger API bans?

**Comment by ddurdle** [comment]
It doesn't generate the number of API calls needed to provoke an API ban.

It doesn't make sense to schedule jobs < 5 mins as the frequency the DBM flushes to disk will likely introduce issues and too frequent writes to the DBM.

**Comment by ddurdle** [comment]
yes
