### ISSUE TITLE
Link to alternate Emby apk that allows direct play of strm files to side load?

### ISSUE THREAD

**Issue by mrmachine** [ddurdle/Python-GoogleDrive-VideoStream#108]
With the official Play Store app forcing strm files to direct stream, I'm still forced to run Emby server on a cloud VPS that has a lot of available bandwidth and good peering to all clients, which negates the primary benefit of using strm files which is a fast connection directly to Google Drive that incurs no additional cost for bandwidth.

**Comment by ddurdle** [comment]
which play store?

**Comment by ddurdle** [comment]
Which app version?  Don't use bleeding edge crap from emby.  Use stable emby app and you shouldn't have an issue.  I have many users Direct Playing without an issue.

**Comment by mrmachine** [comment]
I'm only using the latest stable (I presume) version downloaded from the Google Play Store, and 3.5.3.0 Emby server.

**Comment by ddurdle** [comment]
Issue is resolved with workaround.
