### ISSUE TITLE
Create Docker image and instructions to run via Docker

### ISSUE THREAD

**Issue by mrmachine** [ddurdle/Python-GoogleDrive-VideoStream#109]
`Dockerfile`:
```
FROM alpine:3.7

RUN apk add --update python tini
WORKDIR /opt/pgdvs
COPY . /opt/pgdvs
ENTRYPOINT ["tini", "--", "python", "default.py"]
CMD ["/opt/strm/gdrive.db"]
VOLUME /opt/strm
EXPOSE 9988
```

Usage:
```
$ docker run -d --name=pgdvs --restart always -v /path/to/strm:/opt/strm -p 9988:9988 ddurdle/python-googledrive-videostream
```

Hook it up to Codefresh to automatically build an image for commits pushed to `master` branch and push the resulting image to Docker Cloud/Hub.

On any system where Docker is already installed (e.g. anyone using plexguide to install Emby) can then with a single command have Python-GoogleDrive-VideoStream up and running (and stay up and running across reboots etc.)

They can also use https://github.com/v2tec/watchtower to automatically update it when a new image is pushed to Docker Cloud/Hub:

```
$ docker run -d -e AUTOHEAL_CONTAINER_LABEL=all --name autoheal --restart=always -v /var/run/docker.sock:/var/run/docker.sock willfarrell/autoheal
```

**Comment by GrubbyDungles** [comment]
Fantastic @mrmachine  - I was planning on doing exactly this myself. Thank you.

**Comment by Admin9705** [comment]
ah nice

**Comment by mrmachine** [comment]
@Admin9705 it'd be great if Plex Guide could install this and run it behind traefik

**Comment by GrubbyDungles** [comment]
I'll have a go at it and let you know how I go @mrmachine - Ive added a few containers and had no problems hooking them into traefik via portainer.

**Comment by Sirfrancis17** [comment]
> I'll have a go at it and let you know how I go @mrmachine - Ive added a few containers and had no problems hooking them into traefik via portainer.

I tried to create it through portainer but I could not (image does not exist). What steps would I have to follow?

**Comment by ddurdle** [comment]
For a docker version, see:
https://hub.docker.com/r/rxwatcher/pgdvs-docker
http://hub.docker.com/r/mrmachine/python-googledrive-videostream
https://github.com/choldi/docker-pythongdv

**Comment by mrmachine** [comment]
@ddurdle there are many fixes and changes in this repo not baked into the linked docker images. It'd be great if you could add the Dockerfile and hookup automated builds via Codefresh to this repo, so people can stay up to date.

**Comment by maximuskowalski** [comment]
@mrmachine 
You might want to have a look at 
https://github.com/l3uddz/drive_strm
`cloudb0x/drive_strm`
