### ISSUE TITLE
Error on scheduler?

### ISSUE THREAD

**Issue by MattBlacKK85** [ddurdle/Python-GoogleDrive-VideoStream#115]
Job didn't run
in terminal: 
runtime & status updated
making call to API
exception: 400
exception
In browser:
job #1 username=Emby folder=root every 600 mins looking for changes -- last run status: 2019-01-16 12:46:03.547071 - exception

**Comment by ddurdle** [comment]
git pull the latest and confirm if it still occurs

**Comment by StrangerTwenty** [comment]
I can also say the scheduler doesn't seem to be working for me either from updating to the latest release "v0.1.32".

**Comment by MattBlacKK85** [comment]
did a git pull but still same error. Also looks like login screen isn't working.

**Comment by StrangerTwenty** [comment]
I do have a login set on it.

**Comment by ddurdle** [comment]
whatever the hostname you use in the scheduled job must be added to the /etc/hosts to tell the server it is local.  I believe your issues with this is related to this.  In newer versions of the plugin, external calls to the scheduler are disabled.  Check  what hostname you are using in the scheduled job and add it to your 127.0.0.1 hostname list in /etc/hosts.

**Comment by ddurdle** [comment]
solution provided
