### ISSUE TITLE
Google drive error/ban?

### ISSUE THREAD

**Issue by mkavidas** [ddurdle/Python-GoogleDrive-VideoStream#116]
Seems I'm being banned from gdrive after setting it up: 

"Unable to play this video at this time. The number of allowed playbacks has been exceeded. Please try again later."

This is with only one user.

This is only for the account used for Python-GoogleDrive-VideoStream and happens for all videos (even those shared with me/never used by the app). Videos play fine for other team drive members.

**Comment by ddurdle** [comment]
There is a maximum number of times you can playback a google transcode on an account before limit is reached.  Wait 24 hours for your limit to reset.

**Comment by mkavidas** [comment]
Yea it's working again. Was wondering what that maximum is and how to maybe avoid having that happen? Also google transcode was disabled in the settings when this happened.

**Comment by ddurdle** [comment]
Google doesn't publish the numbers.

How do you disable google transcode?

**Comment by mkavidas** [comment]
In the settings: never transcode: true
