### ISSUE TITLE
Is it possible to make this work with Jellyfin?

### ISSUE THREAD

**Issue by bnichs5** [ddurdle/Python-GoogleDrive-VideoStream#118]
Is it possible to make this work with Jellyfin? The Emby fork. Thanks

**Comment by Drondemovies** [comment]
It is working with Jellyfin.

**Comment by bnichs5** [comment]
Can't get original file to play. only the transcodes work. Any ideas?

**Comment by Drondemovies** [comment]
do you have passthrough=True. What version of Jellyfin you have?

**Comment by bnichs5** [comment]
passthrough is set to false. using jellyfin 10.0.2

**Comment by Drondemovies** [comment]
Set it to true

**Comment by bnichs5** [comment]
did this. video doesnt load now

**Comment by ddurdle** [comment]
Does it work?

**Comment by bnichs5** [comment]
It didn't work for me unfortunately. After a few days of playing around
with it and trying to get it to work I ended up switching to drive_strm for
cloudbox and that worked.
