### ISSUE TITLE
Edit scheduler question

### ISSUE THREAD

**Issue by kinv** [ddurdle/Python-GoogleDrive-VideoStream#125]
Hi, I have the override url set in my scheduled tasks to domain.com. I have changed my domain and want to edit the domain in the current scheduled tasks.
Ive already used your perl script to update the existing strm files (thanks for that its brilliant).

I know it is possible via setup.py to change settings in existing sheduled tasks. Just no idea what im doing. Couldn't figure it out with the info in a previous thread about setup.py

Appreciate it if you can nudge me in the right direction, Cheers!

PS awesome project :)

**Comment by ddurdle** [comment]
You figured it out?  you can change any parameter with "python setup.py -c key value"  You can get a list of all the key-value parameters by running "python setup.py -s"

**Comment by kinv** [comment]
I didn't. I just kept getting exception on the scheduled tasks so deleted them and started again.

This is all python setup.py -s outputs for me;

____________KEY____________ > __________VALUE__________

I didn't know that the parameter for changing the override url was.
