### ISSUE TITLE
 Help, I'm new to everything

### ISSUE THREAD

**Issue by lealvesac** [ddurdle/Python-GoogleDrive-VideoStream#126]
Thank you for helping me. I'm not getting or installing, I use Kodi on the W10, with the normal Gdrive Plugin. I'm trying to install this "videostream" and I can not ... I need a linux machine and emulate Python 2? In order to try to do the description step by step?
Any help from the beginning to the operation will be immensely grateful.

**Comment by ddurdle** [comment]
https://discord.gg/gY4jBGy
