### ISSUE TITLE
Why does WAN transcode

### ISSUE THREAD

**Issue by g0kuz** [ddurdle/Python-GoogleDrive-VideoStream#131]
![1](https://user-images.githubusercontent.com/45234964/56134229-c978af80-5fc0-11e9-866e-c99a2cc25cde.jpg)

File size is 90MB.
1 is downloaded google encoded 480p.
2 is strm of google 480p.
It is the same exact file. Tested= Chrome webplayer, iphone, ipad, android tablet, android phone, nvidia shield tv. All same results.

The difference are
1 (actual file) = Direct Play **WAN** + **Local**
2 (strm) = Direct play **Local** only
2 (strm) = **WAN** transcode initiated, wtf.

Why does it not direct play on WAN? I have port forwarded, change ports and everything. I'd imagine there is something wrong I did because you're using GCE without any problems.

**Comment by g0kuz** [comment]
ContainerBitrateExceedsLimit was found in logs. Don't see its the same problem as yours.

Related to your ios app, https://emby.media/community/index.php?/topic/58821-emby-beta-for-roku-wont-direct-play/

**Comment by g0kuz** [comment]
![2](https://user-images.githubusercontent.com/45234964/56135858-2cb81100-5fc4-11e9-93e5-3c75eda7e175.jpg)

This is the log, look at the point of no return. Bug?

**Comment by ddurdle** [comment]
Which version of emby?

**Comment by g0kuz** [comment]
> Which version of emby?

4.0.2.0

**Comment by ddurdle** [comment]
I have the opposite on 4.0.2 with emby apps for ios and android, always direct playing even if I try to force it to transcode in the app.

Can you add my userid so I can test?  ddurdle1

**Comment by g0kuz** [comment]
> ddurdle1

Done, sent invitation.

**Comment by ddurdle** [comment]
ddurdle on discord

**Comment by ddurdle** [comment]
![image](https://user-images.githubusercontent.com/851508/56148634-b6da8800-5f78-11e9-8399-60228ff1c39f.png)

**Comment by ddurdle** [comment]
You said you tried the ios app?  I see the transcoding is trying to use the default emby 4.0.2 ffmpeg with google transcode (which doesn't work on ios).  It requires an older emby ffmpeg that I have available.

But it is attempting to transcode, which is different then what I encounter on my emby servers.
