### ISSUE TITLE
[Question]How to import Kodi plugin settings file?

### ISSUE THREAD

**Issue by Markhor123** [ddurdle/Python-GoogleDrive-VideoStream#137]

**Comment by ddurdle** [comment]
python setup.py 
Usage: setup.py [option] <key> <value>

Options:
  -h, --help            show this help message and exit
  -a ADD, --add=ADD     Add Settings
  -c CHANGE, --change=CHANGE
                        Change Settings
  -s, --show            Display Settings
  -i IMP, --import=IMP  Import Settings
  -r REMOVE, --remove=REMOVE
                        Remove Settings
  -d DATABASE, --dbase=DATABASE
                        change database


python setup.py -i settings.xml
