### ISSUE TITLE
Server resolver url

### ISSUE THREAD

**Issue by maximilianh75** [ddurdle/Python-GoogleDrive-VideoStream#27]
I test the playback addon and work only at server level, work with emby clients only using streaming or transcoding, NOT direct play. 
I ask you if you could develope some method to the server resolve the url and send to client because i don't want to use server broadband for client when i can use google, the other way the emby server have to upstream the google drive video to then the user client downstream and that be an innecesary loop

**Comment by maximilianh75** [comment]
OK I RESOLVE OPEN THE PORT IN MY VPS
Add this for someone get stuck with port issue

**Comment by ddurdle** [comment]
there is a passthrough setting as well, but I have not added it to the settings pane yet.  It can be set using the setup.py script (such as python setup -d gdrive.db -a passthrough true)

**Comment by maximilianh75** [comment]
How invoque in a strm different qualities of a video (naming). Do you have any manual of strm how to manual naming

**Comment by ddurdle** [comment]
so you mean like a parameter inside a STRM file that tells it to select transcode 720p?

**Comment by maximilianh75** [comment]
No, Emby Server automatic transcode or remux if can't direct play, And that happend because the socket 9988 was closed, When I opened all get fixed.

**Comment by maximilianh75** [comment]
Yes, A parameter to select a stream or other inside a movie. 720p or original

**Comment by ddurdle** [comment]
there is already a parameter you can add to the URL or to a STRM to force original regardless of the user's preference.

Adding 
&original=true 
to the URL will force the playback to original quality. 

Please confirm this works for you.

 I will create a separate change issue for adding transcode selection using same method

**Comment by maximilianh75** [comment]
works with playvideo mode automatic play original, If i want stream transcode what'is the parameter example

**Comment by ddurdle** [comment]
I'm testing this feature but it is not ready for public testing yet.

**Comment by ddurdle** [comment]
in https://github.com/ddurdle/Python-GoogleDrive-VideoStream/issues/29
