### ISSUE TITLE
Add support for specifying transcode type in URL

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Python-GoogleDrive-VideoStream#29]
For STRM files and playback URLs, to force quality to a specific transcode.

Similar to forcing original quality with &original=true

**Comment by ddurdle** [comment]
as discussed in https://github.com/ddurdle/Python-GoogleDrive-VideoStream/issues/27

**Comment by ddurdle** [comment]
in 0.1.10

**Comment by maximilianh75** [comment]
Can you integrate a tool to resolve the transcoded video link to work in client level- Without tunneling
