### ISSUE TITLE
Direct play

### ISSUE THREAD

**Issue by maximilianh75** [ddurdle/Python-GoogleDrive-VideoStream#32]
I have a question
I'm testing the server.py and find that all movie pass against the tunnel you do it 9988, it's any possibility to only resolve and send playable link to client. Example
A web browser in somewhere enter, access to emby server that's locate in another place and execute a movie that's in google drive 
In that case i need the server only send link to client browser and not downstream the movie and upstream to the client

**Comment by maximilianh75** [comment]
It's any possible to add the fetch function you have in your other app Python-GoogleDrive-StaticLinks
to VideoStream???

**Comment by ddurdle** [comment]
When you enable passthrough = true, the return URL is a URL the client downstreams directly from Google Drive.  It does not work with Google transcoded files though.
