### ISSUE TITLE
buildstrm folders not working

### ISSUE THREAD

**Issue by maximilianh75** [ddurdle/Python-GoogleDrive-VideoStream#40]
When I try to use build stream over a folder to make a lot of strm files at same time send me : 
This page isn’t working
The same  with Generate/Save TV/Movie STRM
Any idea what happen that because i can make strm files one by one

**Comment by ddurdle** [comment]
Is there an error in the console displayed?

**Comment by maximilianh75** [comment]
here screenshot of error
https://imgur.com/yXRmHno

**Comment by ddurdle** [comment]
I'll investigate

**Comment by ddurdle** [comment]
I investigated and identified the issue is tied to the enablement of automatic STRM for testing (when the change ID = 0).  developing fix.

**Comment by ddurdle** [comment]
please test in 0.1.11

**Comment by maximilianh75** [comment]
I test and now work fine, the only question is if you can make a resolve function to access to multiple resolution using passtrough function because i know that gdrive generate a an unique ID related to the IP that access to stream.
You construct a tunnel, anny posibility to use api gdrive to generate transcoded links to ip client adress??

**Comment by ddurdle** [comment]
What emby client and devices will your users be using?
