### ISSUE TITLE
catalog strms to false stops transcoding AND original streams being created

### ISSUE THREAD

**Issue by Dec64** [ddurdle/Python-GoogleDrive-VideoStream#53]
Setting 
`catalog STRMs into folders according to movie/tv/other?` to `false`
`create original quality STRM files` to `true` ,
`create google transcode quality STRM files?` to `true`

results in ONLY creating the original strm files.

**Comment by ddurdle** [comment]
most current master contains a fix for generation of multiple STRMs.  additional work needed for when generating a single STRM.

**Comment by ddurdle** [comment]
completed.
