### ISSUE TITLE
Add an option to reset the runtime status of scheduled jobs

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Python-GoogleDrive-VideoStream#59]
Sometimes jobs can become stuck in running if the service is stopped while running.  The user can reset the status by running on the command line "python setup.py -c #_status 0" where # is the job number.  

Add an option to the + menu to reset the job status

**Comment by marilson8** [comment]
Good evening buddy :)

so, i've been using the new schedule tasks, and, I created 2 jobs for export two differents profile, so the point is:

the status of the two jobs started with: -- last run status: 2018-05-26 19:29:18.833636 - Created 0 STRM file(s). (changetoken = ) +........

then, after a while, one of the two, stops to export and just appear as: -- running

see an example:

![image](https://user-images.githubusercontent.com/22123799/40580769-f0aef82c-6113-11e8-9a0a-a00c5d7d593d.png)

none error appear in prompt

**Comment by marilson8** [comment]
If I reset the job or reset the plugin service, it works again, and then the error returns after a while, and again and again

**Comment by marilson8** [comment]
detail: i set to export every 1 min each job

**Comment by ddurdle** [comment]
If you restart the plugin while jobs are running, they remain in "running"
state.

**Comment by ddurdle** [comment]
There might be warrant to reset jobs automatically upon startup, but I'm reviewing if that could introduce issues.

**Comment by marilson8** [comment]
when one of the two jobs are on the status: running
it dont export until reset the job or the plugin. It seems to be stuck because it does not go out of this status and does not export anything else.

After I reset the job stuck, it works again looks:

![image](https://user-images.githubusercontent.com/22123799/40582855-839b74cc-614f-11e8-9e29-4b68f7101120.png)

**Comment by marilson8** [comment]
I usually update the web page to see if it exits the running status, but it does not go out and why it gets stuck

**Comment by ddurdle** [comment]
I have the plugin running on 4 test servers and I haven't run into a scheduled job that stays locked in "running" unless I accidentally kill/stop the plugin while job is running.

If a job fails, it will go into "exception" and rerun next scheduled time.

I have updated the code today to ensure that on startup, any stuck "running" jobs are reset to "ready" and they will run next scheduled time.

**Comment by marilson8** [comment]
Can you test, running two scheduled jobs both set to 1 min to export, to see what happens? i think one interrupt the other, 'cause the time

**Comment by marilson8** [comment]
i'll test, set one job to 1min and the other in 2min

**Comment by ddurdle** [comment]
Are the folders team drives or folders on My Drive?

**Comment by ddurdle** [comment]
You add a video file to the drive and don't see count go up by 1?  The count will reset to 0 time after that if no files are received.

**Comment by marilson8** [comment]
team drives

**Comment by marilson8** [comment]
exacly, i upload a video, and then, goes for 5min, 10min, 20min and none export, then i'll go check what happens and:

![image](https://user-images.githubusercontent.com/22123799/40660652-a419a51c-631f-11e8-87ed-cc519627a5b9.png)

the above job, is ok, but the top needs to be reseted

**Comment by marilson8** [comment]
when I reset:

![image](https://user-images.githubusercontent.com/22123799/40660809-1cec5cd2-6320-11e8-9797-192d96a8d18d.png)
that time, both are working perfectly, after a while, one of the two return with --running, and must be reseted again

**Comment by ddurdle** [comment]
In settings pane, can you input a log file (such as /tmp/scheduler.log)?  The log will document the runs and may be helpful in narrowing the cause.

**Comment by ddurdle** [comment]
In settings pane, can you input a log file (such as /tmp/scheduler.log)?
The log will document the runs and may be helpful in narrowing the cause.

**Comment by marilson8** [comment]
of course, ty, i'll do it

**Comment by marilson8** [comment]
in Debug mode, false or true?

**Comment by ddurdle** [comment]
![image](https://user-images.githubusercontent.com/851508/40727500-ff5f59c2-63f5-11e8-9fd8-88334a8d9728.png)
In the example, job #16 is running every 1 min and after the run at 1527654416, job #20 with a timestamp earlier then the most current #16 runs, and then job #19 with an even earlier timestamp.  Then job #16 never runs again (presumably the timestamp gets reset by job #20 or #19

**Comment by marilson8** [comment]
He did not generate in the folder, why?

**Comment by ddurdle** [comment]
You need to ensure the path exists to the file you specify.

**Comment by marilson8** [comment]
i'm using it on cygwin, only have windows paths to put, maybe this is the cause

**Comment by ddurdle** [comment]
you should be able to input a path such as c:\scheduler.log

**Comment by marilson8** [comment]
ow, i was putting: c:, i'm correcting now

**Comment by marilson8** [comment]
![image](https://user-images.githubusercontent.com/22123799/40732039-6b434766-6400-11e8-9917-64f3718a4aa1.png)

**Comment by marilson8** [comment]
when i saved, it substitute the '\' to '%5C'

**Comment by ddurdle** [comment]
I'll track that issue here: https://github.com/ddurdle/Python-GoogleDrive-VideoStream/issues/62

I believe you can use c:/path in meanwhile

**Comment by marilson8** [comment]
thanx

**Comment by ddurdle** [comment]
minor fix, I was accidentally filtering for %5c and not %5C

**Comment by marilson8** [comment]
i get it

**Comment by ddurdle** [comment]
Ruled out previous statement about timing of other job updates conflicting.

I dd witness that at the time the job is left in running status, the runtime epoch for the job is not updated for the current run.

**Comment by ddurdle** [comment]
completed.
