### ISSUE TITLE
add additional STRM parameter to maintain folder structure

### ISSUE THREAD

**Issue by ddurdle** [ddurdle/Python-GoogleDrive-VideoStream#73]
- could you enable preserving the directory structure when cataloging is enabled?
-  keep the directory structure the way it is but rename the generated strms so emby can group duplicate movies and tv shows properly

**Comment by fabioneves** [comment]
+1

**Comment by ddurdle** [comment]
Nobody used this parameter and it is too hard to maintain so many (unused) parameters.  Creates too much work.

The user should decide if it wants to let the plugin categorize the video files (catalog = true) or they will categorize the files themselves (catalog = false).  To have it semi-so where you have the plugin catalog the media but you want to retain folder structure just introduces too much confusion for the average user, and as a result, nobody understands or uses the new parameter.
