### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by SteveMalso** [ddurdle/Python-GoogleDrive-VideoStream#94]
Is it normal for videos to start a lot slower in emby than playing back videos directly through the server via a browser?

Takes around 30 seconds to start video playback via emby while it's almost instantaneous through a browser and your Kodi plugin.

**Comment by SteveMalso** [comment]
I see the issue. When playing a video from the emby web client, it creates a minutes worth of buffer. Curious if you experience this too.

**Comment by ddurdle** [comment]
Playback starts within 3 seconds for me.
