### ISSUE TITLE
change audio track

### ISSUE THREAD

**Issue by mkavidas** [ddurdle/Python-GoogleDrive-VideoStream#95]
Would it be possible to change audio track of STRM files? Some movies have multiple audio tracks and it would be nice to be able to change the audio track. Maybe somehow default to a language.

Edit: This seems to be a Google drive issue as far as I can tell.

**Comment by mkavidas** [comment]
You can change audio tracks on the GDrive-for-KODI addon when streaming original quality so I'm sure it is possible. Am I doing something wrong or is the functionality missing?

**Comment by mkavidas** [comment]
Is there a way to fix this without setting never_transcode to true? I would like to take advantage of google transcodes. Setting never_transcode to true eats up all my bandwidth.

**Comment by ddurdle** [comment]
Google transcodes only support one audio track
