### ISSUE TITLE
How difficult would it be to convert this to a Kodi plugin?

### ISSUE THREAD

**Issue by SteveMalso** [ddurdle/Python-GoogleDrive-VideoStream#96]
Would save me the trouble of having to download the package on different systems, setting up background tasks to run default.py and having to download python on windows machines.

**Comment by mkavidas** [comment]
There already is a kodi plugin: https://github.com/ddurdle/GDrive-for-KODI

**Comment by GangaBanga** [comment]
Indeed there is, however if I have STRM files that point to the gdrive Kodi plugin in an emby server, neither resume nor watch status' update in emby... using the emby for kodi addon. Also resume/watched status don't work using the gdrive Kodi plugin on its own. The solution to get resume support and watched status' to function is the following.

I have a emby server that has a library of STRM files that point to Python-GoogleDrive-VideoStream. This is great as all Kodi devices have a real time synced library. I need to have VideoStream running on different machines as they are on different home networks.

You may be wondering why don't I just run VideoStream on the server that contains the emby server... well my peering to that server is shit so I experience buffering, plus it has limited upload bandwidth.

**Comment by SteveMalso** [comment]
Indeed there is, however if I have STRM files that point to the gdrive for Kodi plugin in an emby library, resume and watched status' don't update using the emby for Kodi addon. Neither do resume/watched status' work when using the gdrive for Kodi plugin on its own. The solution to getting resume and watched statuses to work is the following:

I have an emby server with a library of STRM files that point to Python-GoogleDrive-VideoStream. This is great as all Kodi libraries are synced in real time with the added benefit of emby's superior metadata scraping. I need to have VideoStream running on different machines as they are on different home networks.

You may be wondering why don't I just run VideoStream on the server that runs emby server, well that server has bad peering to my country so I experience buffering. Plus it has limited upload bandwidth.

**Comment by ddurdle** [comment]
Use Passthrough = true to have the videostream / emby stream to direct from
Google Drive to the user.

What is needed is a small helper plugin that lets Google Transcode streams
pass direct to KODI from videostream via Google Drive (requires CORs
support, not provided by Emby).  A small "helper" plugin would resolve this
shortfall.

Also,  a way to keep the STRMs updated on KODI.  I am not a huge fan of the
emby on KODI as it often errors out, asking for KODI restart.

**Comment by SteveMalso** [comment]
Cheers for replying ddurdle.

The passthrough feature won't help me unfortunately as my media is encrypted. Haven't had issues with emby for kodi personally, apart from no resume/watched status support for STRMs that point to your gdrive addon.
